# Generated by Django 2.2.4 on 2023-02-27 15:14
from django.db import migrations
from django.db.models import F


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(owners_phonenumber__isnull=False).update(owner_pure_phone=F('owners_phonenumber'))


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_auto_20230227_1912'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
